Blog/Areas/Admin/Controllers/TagController.cs
using Blog.Entities.Models;
using Blog.Infrastructure.Interfaces.Admin;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Blog.Areas.Admin.Controllers
{
    [Area("admin")]
    [Authorize]
    public class TagController : Controller
    {
        private readonly ITagService _tagService;

        public TagController(ITagService tagService)
        {
            _tagService = tagService;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Tag> tags = await _tagService.GetAll();

            return View(tags);
        }

        public IActionResult Create()
        {
            return View("Edit", new Tag { });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Tag tag)
        {
            if (ModelState.IsValid)
            {
                await _tagService.Create(tag);

                return RedirectToAction(nameof(Index));
            }

            return View("Edit", tag);
        }

        public async Task<IActionResult> Update(string id)
        {
            Tag tag = await _tagService.GetById(id);

            if (!string.IsNullOrEmpty(id))
            {
                return View("Edit", tag);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Tag tag)
        {
            if (ModelState.IsValid)
            {
                await _tagService.Update(tag);

                return RedirectToAction(nameof(Index));
            }

            return View("Edit", tag);
        }

        public async Task<PartialViewResult> Delete(string id)
        {
            Tag tag = await _tagService.GetById(id);

            return PartialView("_DeleteTagModalPartial", tag);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Tag tag)
        {
            try
            {
                _tagService.Delete(tag.Id);
            }
            catch
            {
                ViewBag.Error = "Some error occured please try again later.";
            }

            return RedirectToAction(nameof(Index)); ;
        }
    }
}

Blog/Areas/Admin/Views/Tag/Edit.cshtml
@model Tag

<div class="page-heading">
    <h1 class="page-title">New Tag</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a asp-action="Index">Tag</a>
        </li>
        @if (Model != null && Model.Id != null)
        {
            <li class="breadcrumb-item"> <a asp-action="Edit">Edit</a> </li>
        } else
        {
            <li class="breadcrumb-item"> <a asp-action="Create">Create</a> </li>
        }
    </ol>
</div>
<div class="page-content fade-in-up">
    <div class="ibox">
        <div class="ibox-body">
            <form asp-action="@ViewContext.RouteData.Values["action"]" asp-antiforgery="true" class="form-horizontal" id="form-sample-1" method="post" novalidate="novalidate">
                @if (Model != null && Model.Id != null)
                {
                    <input asp-for="Id" hidden />
                }

                <div class="form-group row @(ViewData.ModelState["TagName"] != null? "has-error" : "")">
                    <label asp-for="Name" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <input class="form-control" asp-for="Name" />
                        <span asp-validation-for="Name" class="help-block"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10 ml-sm-auto">
                        <button class="btn btn-primary" type="submit">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section JS {
    <link href="~/assets/vendors/select2/dist/js/select2.full.min.js" rel="stylesheet" />
}

Blog/Areas/Admin/Views/Tag/Index.cshtml
@model IEnumerable<Tag>

<div class="ibox">
    <div class="ibox-body">
        <h5 class="font-strong mb-4"></h5>
        <div class="flexbox mb-4">
            <div class="flexbox">
                <span class="mr-4 static-badge badge-pink"><i class="la la-pencil"></i></span>
                <div>
                    <h5 class="font-strong">Tag</h5>
                    <div class="text-light">Found @Model.Count() tags</div>
                </div>
                <div class="ml-4">
                    <a asp-action="Create" class="btn btn-success">Add Tag</a>
                </div>
            </div>
            <div class="input-group-icon input-group-icon-left mr-3">
                <span class="input-icon input-icon-right font-16"><i class="ti-search"></i></span>
                <input class="form-control form-control-rounded form-control-solid" id="key-search" type="text" placeholder="Search ...">
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered table-hover" id="datatable">
                <thead class="thead-default thead-lg">
                    <tr>
                        <th>Tag Name</th>
                        <th class="no-sort"></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model?.Count() > 0)
                    {
                        @foreach (var tag in Model)
                        {
                            <tr>
                                <td>
                                    @tag.Name
                                </td>
                                <td>
                                    <a class="btn btn-info" asp-action="update" asp-route-id="@tag.Id">
                                        <i class="la la-pencil"></i>
                                        <span>
                                            Edit
                                        </span>
                                    </a>
                                    <a class="btn btn-danger" href="javascript:;" data-toggle="modal" data-target="#delete-tag-modal-@tag.Id">
                                        <i class="ti-trash"></i>
                                        <span>
                                            Delete
                                        </span>
                                    </a>
                                    <partial name="_DeleteTagModalPartial" model="tag" />
                                </td>
                            </tr>
                        }

                    } else
                    {
                        <tr>
                            <td>
                                No Categories
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Blog/Areas/Admin/Views/Tag/_DeleteTagModalPartial.cshtml
@model Tag

<div class="modal fade" id="delete-tag-modal-@Model.Id">
    <div class="modal-dialog" style="width:400px;" role="document">
        <div class="modal-content timeout-modal">
            <div class="modal-body">
                <button class="close" data-dismiss="modal" aria-label="Close"></button>
                <div class="text-center h3 mb-3">@Model.Name</div>
                <form asp-controller="Tag" asp-action="Delete" method="post">
                    <div id="timeout-activate-box">
                        <div class="text-center">
                            <input asp-for="Id" hidden />
                            <button type="submit" class="btn btn-primary btn-fix btn-air">Delete</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>